name: Check

on: workflow_dispatch

jobs:
  actionlint:
    name: Lint GitHub workflows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download actionlint
      id: get_actionlint
      run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
    - name: Check GitHub workflows
      run: ${{ steps.get_actionlint.outputs.executable }} -color

  check:
    name: Check gradle build
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Setup java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
    - name: Assemble Releasae
      shell: bash
      run: |
        ./gradlew assembleRelease
        DIRNAME=upload/termux-debug-apks-"$GITHUB_SHA"
        mkdir -p "$DIRNAME"
        shopt -s globstar; for file in termux-*/**/*.apk; do FILENAME="$(basename "$file")"; cp "$file" "$DIRNAME"/"${FILENAME/.apk/-$GITHUB_SHA.apk}"; done
    - uses: actions/upload-artifact@v4
      with:
        name: termux-debug-apks-${{ github.sha }}
        path: upload/

  gradle-wrapper-validation:
    name: Validate gradle wrappers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
